In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import plotly.express as px

In [ ]:
df=pd.read_csv('/content/all_wc_18_players_fifa.csv')

In [ ]:
df

,team,number,position,birth_date,shirt_name,club,height,weight,league,age,name,caps
0,Argentina,1,GK,1986-02-10,GUZMÁN,Tigres UANL,192,90,MEX,32.339726,Nahuel Guzmán,6
1,Argentina,2,DF,1987-03-18,MERCADO,Sevilla FC,181,81,ESP,31.241096,Gabriel Mercado,20
2,Argentina,3,DF,1992-08-31,TAGLIAFICO,AFC Ajax,169,65,NED,25.786301,Nicolás Tagliafico,4
3,Argentina,4,DF,1986-09-20,ANSALDI,Torino FC,181,73,ITA,31.731507,Cristian Ansaldi,5
4,Argentina,5,MF,1986-01-30,BIGLIA,AC Milan,175,73,ITA,32.369863,Lucas Biglia,57
...,...,...,...,...,...,...,...,...,...,...,...,...
731,Uruguay,19,DF,1990-10-07,S. COATES,Sporting CP,196,89,POR,27.684932,Sebastián Coates,30
732,Uruguay,20,FW,1990-03-19,J. URRETAVISCAYA,CF Monterrey,172,66,MEX,28.238356,Jonathan Urretaviscaya,4
733,Uruguay,21,FW,1987-02-14,E. CAVANI,Paris Saint-Germain FC,188,78,FRA,31.328767,Edinson Cavani,101
734,Uruguay,22,DF,1987-04-07,M. CACERES,SS Lazio,178,75,ITA,31.186301,Martín Cáceres,76
735,Uruguay,23,GK,1983-03-25,M. SILVA,CR Vasco da Gama,187,82,BRA,35.221918,Martín Silva,11

In [ ]:
df.shape

(736, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   team        736 non-null    object
 1   number      736 non-null    int64
 2   position    736 non-null    object
 3   birth_date  736 non-null    object
 4   shirt_name  736 non-null    object
 5   club        736 non-null    object
 6   height      736 non-null    int64
 7   weight      736 non-null    int64
 8   league      736 non-null    object
 9   age         736 non-null    float64
 10  name        736 non-null    object
 11  caps        736 non-null    int64
dtypes: float64(1), int64(4), object(7)
memory usage: 69.1+ KB

In [ ]:
df.isna().sum()

team          0
number        0
position      0
birth_date    0
shirt_name    0
club          0
height        0
weight        0
league        0
age           0
name          0
caps          0
dtype: int64

No null values found

In [ ]:
df1=df.groupby('team')[['height']].mean()
df1

                  height
team
Argentina     178.434783
Australia     180.869565
Belgium       185.347826
Brazil        180.782609
Colombia      180.782609
Costa Rica    180.695652
Croatia       185.260870
Denmark       186.608696
Egypt         181.000000
England       182.739130
France        183.304348
Germany       185.782609
Iceland       185.521739
Iran          184.478261
Japan         178.782609
Mexico        179.782609
Morocco       182.695652
Nigeria       184.521739
Panama        182.173913
Peru          177.608696
Poland        183.173913
Portugal      179.739130
Russia        184.391304
Saudi Arabia  177.652174
Senegal       183.652174
Serbia        186.695652
South Korea   181.869565
Spain         179.913043
Sweden        185.739130
Switzerland   182.913043
Tunisia       183.086957
Uruguay       181.043478

In [ ]:
fig=px.bar(df1,title='The average height of players from each country.')
fig.show()

In [ ]:
#The tallest player(s) during the tournament
df.nlargest(5,['height','weight'])

,team,number,position,birth_date,shirt_name,club,height,weight,league,age,name,caps
149,Croatia,12,GK,1990-04-03,L. KALINIĆ,KAA Gent,201,96,BEL,28.197260,Lovre Kalinić,11
163,Denmark,3,DF,1992-08-03,VESTERGAARD,VfL Borussia Mönchengladbach,200,98,GER,25.863014,Jannik Vestergaard,16
46,Belgium,1,GK,1992-05-11,COURTOIS,Chelsea FC,199,91,ENG,26.093151,Thibaut Courtois,58
5,Argentina,6,DF,1987-03-17,FAZIO,AS Roma,199,85,ITA,31.243836,Federico Fazio,9
287,Iceland,12,GK,1995-01-19,SCHRAM,Roskilde BK,198,92,DEN,23.400000,Frederik Schram,4

Lovre Kalinic is the tallest player in the tournament,he belongs to Croatia

In [ ]:
#The shortest players during the tournament
df.nsmallest(5,['height','weight'])

,team,number,position,birth_date,shirt_name,club,height,weight,league,age,name,caps
455,Panama,19,MF,1987-12-18,QUINTERO,Universitario Lima,165,62,PER,30.487671,Ricardo Ávila,5
559,Saudi Arabia,8,MF,1990-06-26,YAHIA,CD Leganés,165,63,ESP,27.967123,Yahya Al-Shehri,57
689,Switzerland,23,MF,1991-10-10,SHAQIRI,Stoke City FC,165,78,ENG,26.676712,Xherdan Shaqiri,70
387,Mexico,20,MF,1990-02-11,J. AQUINO,Tigres UANL,166,59,MEX,28.336986,Javier Aquino,53
404,Morocco,14,MF,1984-08-15,BOUSSOUFA,Al Jazira,167,59,UAE,33.830137,Mbark Boussoufa,59

Three players we found,Ricardo Avila from PANAMA,Yahya-Al-Shehri from SAUDI ARABIA,Xherdan Shaqiri from SWITZERLAND

In [ ]:
#The average weight of players from each country
df2=df.groupby('team')[['weight']].mean()
df2

                 weight
team
Argentina     75.565217
Australia     77.739130
Belgium       79.565217
Brazil        76.565217
Colombia      76.173913
Costa Rica    74.130435
Croatia       79.304348
Denmark       82.608696
Egypt         78.434783
England       78.826087
France        80.000000
Germany       80.043478
Iceland       80.739130
Iran          78.130435
Japan         71.521739
Mexico        74.086957
Morocco       74.652174
Nigeria       80.478261
Panama        80.000000
Peru          75.869565
Poland        76.478261
Portugal      73.608696
Russia        77.608696
Saudi Arabia  73.043478
Senegal       76.826087
Serbia        80.521739
South Korea   74.434783
Spain         74.739130
Sweden        78.826087
Switzerland   79.913043
Tunisia       75.000000
Uruguay       74.608696

In [ ]:
fig=px.bar(df2,color='value',title='The average weight of players from each country')
fig.show()

In [ ]:
#Depicting heeight']].mean()ight-weight relations of players in a tournament
df3=df.groupby('height')[['weight']].mean()
df3

           weight
height
165     67.666667
166     59.000000
167     64.250000
168     65.666667
169     66.307692
170     66.466667
171     70.000000
172     69.058824
173     70.000000
174     71.400000
175     70.454545
176     72.000000
177     73.894737
178     74.853659
179     72.000000
180     75.113636
181     76.290323
182     76.405405
183     78.292683
184     78.096774
185     78.226415
186     79.454545
187     81.564103
188     82.366667
189     81.193548
190     82.655172
191     84.368421
192     84.000000
193     89.400000
194     87.900000
195     90.222222
196     88.142857
197     88.400000
198     90.500000
199     88.000000
200     98.000000
201     96.000000

In [ ]:
fig=px.line(df3,title='Height-Weight Relationship')
fig.show()

In [ ]:
df4=df.groupby('league')[['team']].count()

In [ ]:
#Participation of players from each league
df4

        team
league
ARG        9
AUS        3
AUT        2
BEL       16
BRA        9
BUL        2
CAN        1
CHI        2
CHN        8
COL        6
CRC        7
CRO        3
DEN        8
EGY       10
ENG      124
ESP       81
FIN        1
FRA       49
GER       67
GRE        5
GUA        2
GUI        1
HON        1
IRN        9
ISL        1
ISR        2
ITA       58
JPN       15
KOR       13
KSA       30
MAR        2
MEX       22
NED       15
NGA        1
NOR        1
PAN        3
PER        7
POL        4
POR       19
QAT        2
ROU        1
RSA        1
RUS       36
SCO        7
SRB        3
SUI        4
SVK        1
SWE        3
TUN        6
TUR       22
UAE        2
UKR        3
URU        2
USA       18
WAL        6

In [ ]:
fig=px.bar(df4,title='Participation of players from each league')
fig.show()

Most of players participating in  English permier league,secondly Spanish,then German

In [ ]:
df5=df.groupby('league')[['age']].mean()

In [ ]:
df5

              age
league
ARG     25.855708
AUS     23.638356
AUT     22.060274
BEL     27.523630
BRA     29.356164
BUL     26.791781
CAN     30.449315
CHI     30.083562
CHN     30.183219
COL     33.147489
CRC     31.334638
CRO     26.134247
DEN     27.067466
EGY     29.043836
ENG     27.662240
ESP     27.596922
FIN     32.920548
FRA     26.552586
GER     26.600818
GRE     28.679452
GUA     37.278082
GUI     33.191781
HON     29.767123
IRN     27.582344
ISL     33.589041
ISR     26.384932
ITA     27.857109
JPN     26.780639
KOR     28.755532
KSA     29.732329
MAR     23.580822
MEX     29.382939
NED     26.255708
NGA     29.660274
NOR     22.306849
PAN     29.243836
PER     28.863014
POL     30.006164
POR     26.626099
QAT     26.030137
ROU     36.715068
RSA     32.268493
RUS     28.554871
SCO     30.037965
SRB     28.135160
SUI     26.730822
SVK     27.205479
SWE     23.389041
TUN     26.753881
TUR     30.203238
UAE     32.827397
UKR     28.354338
URU     28.964384
USA     27.696347
WAL     28.818265

In [ ]:
fig=px.bar(df5,color='value',title='Average age of players from each country')
fig.show()

The heighest average is 37.27 and lowest 22.30,the best average of age is in between 26 and 29.5

In [ ]:
players_Cap=df[df['caps'] >= 100]

In [ ]:
players_Cap

,team,number,position,birth_date,shirt_name,club,height,weight,league,age,name,caps
9,Argentina,10,FW,1987-06-24,MESSI,FC Barcelona,170,72,ESP,30.972603,Lionel Messi,124
13,Argentina,14,DF,1984-06-08,MASCHERANO,Hebei China Fortune FC,174,73,CHN,34.016438,Javier Mascherano,143
26,Australia,4,FW,1979-12-06,CAHILL,Millwall FC,180,76,ENG,38.520548,Tim Cahill,106
50,Belgium,5,DF,1987-04-24,VERTONGHEN,Tottenham Hotspur FC,189,86,ENG,31.139726,Jan Vertonghen,102
119,Costa Rica,5,MF,1988-05-27,C. BORGES,Deportivo La Coruña,187,79,ESP,30.049315,Celso Borges,113
124,Costa Rica,10,MF,1985-08-18,BRYAN,Sporting CP,187,73,POR,32.821918,Bryan Ruiz,110
147,Croatia,10,MF,1985-09-09,MODRIĆ,Real Madrid CF,172,66,ESP,32.761644,Luka Modrić,106
184,Egypt,1,GK,1973-01-15,ELHADARY,Al Taawoun FC,190,90,KSA,45.410959,Essam El-Hadary,158
190,Egypt,7,DF,1984-11-10,A. FATHI,Al Ahly SC,176,76,EGY,33.591781,Ahmed Fathy,126
326,Japan,5,DF,1986-09-12,NAGATOMO,Galatasaray SK,170,68,TUR,31.753425,Yuto Nagatomo,105
330,Japan,9,FW,1986-04-16,OKAZAKI,Leicester City FC,174,70,ENG,32.161644,Shinji Okazaki,113
338,Japan,17,MF,1984-01-18,HASEBE,Eintracht Frankfurt,180,72,GER,34.402740,Makoto Hasebe,110
360,South Korea,16,MF,1989-01-24,S Y KI,Swansea City AFC,186,75,WAL,29.386301,Ki Sung-yueng,102
371,Mexico,4,DF,1979-02-13,R. MÁRQUEZ,CF Atlas,184,77,MEX,39.331507,Rafael Márquez,145
377,Mexico,10,MF,1989-05-11,G. DOS SANTOS,LA Galaxy,178,70,USA,29.093151,Giovani dos Santos,105
381,Mexico,14,FW,1988-06-01,J. HERNÁNDEZ,West Ham United FC,175,71,ENG,30.035616,Javier Hernández,102
385,Mexico,18,MF,1986-09-28,A. GUARDADO,Real Betis,167,63,ESP,31.709589,Andrés Guardado,145
437,Panama,1,GK,1981-09-26,PENEDO,Dinamo Bucharest,183,70,ROU,36.715068,Jaime Penedo,131
441,Panama,5,DF,1986-03-20,R. TORRES,Seattle Sounders FC,188,99,USA,32.235616,Román Torres,111
442,Panama,6,MF,1984-05-29,GOMEZ,Atlético Bucaramanga,183,82,COL,34.043836,Gabriel Gómez,144
443,Panama,7,FW,1981-03-13,PEREZ,CSD Municipal,187,83,GUA,37.254795,Blas Pérez,118
454,Panama,18,FW,1982-03-28,TEJADA,Sport Boys,183,87,PER,36.213699,Luis Tejada,105
459,Panama,23,DF,1981-02-24,BALOY,CSD Municipal,185,87,GUA,37.301370,Felipe Baloy,102
512,Portugal,7,FW,1985-02-05,RONALDO,Real Madrid CF,185,80,ESP,33.353425,Cristiano Ronaldo,150
513,Portugal,8,MF,1986-09-08,J. MOUTINHO,AS Monaco,170,61,FRA,31.764384,João Moutinho,110
529,Russia,1,GK,1986-04-08,AKINFEEV,CSKA Moscow,185,83,RUS,32.183562,Igor Akinfeev,106
532,Russia,4,DF,1979-07-14,IGNASHEVICH,CSKA Moscow,186,84,RUS,38.917808,Sergei Ignashevich,122
554,Saudi Arabia,3,DF,1984-03-31,OSAMA,Al Hilal SFC,188,83,KSA,34.205479,Osama Hawsawi,135
568,Saudi Arabia,17,MF,1984-07-25,TAISEER,Al Ahli SC,169,69,KSA,33.887671,Taisir Al-Jassim,132
603,Serbia,6,DF,1984-02-22,IVANOVIĆ,FC Zenit St. Petersburg,185,89,RUS,34.306849,Branislav Ivanović,103
625,Spain,5,MF,1988-07-16,SERGIO,FC Barcelona,189,78,ESP,29.912329,Sergio Busquets,103
626,Spain,6,MF,1984-05-11,A. INIESTA,FC Barcelona,171,68,ESP,34.093151,Andrés Iniesta,127
635,Spain,15,DF,1986-03-30,RAMOS,Real Madrid CF,183,75,ESP,32.208219,Sergio Ramos,152
641,Spain,21,FW,1986-01-08,SILVA,Manchester City FC,170,67,ENG,32.430137,David Silva,121
650,Sweden,7,MF,1985-06-06,LARSSON,Hull City FC,178,70,ENG,33.021918,Sebastian Larsson,100
668,Switzerland,2,DF,1984-01-16,LICHTSTEINER,Juventus FC,181,77,ITA,34.408219,Stephan Lichtsteiner,100
715,Uruguay,3,DF,1986-02-16,D. GODIN,Atletico Madrid,185,73,ESP,32.323288,Diego Godín,116
719,Uruguay,7,MF,1985-09-30,C. RODRIGUEZ,CA Penarol,178,79,URU,32.704110,Cristian Rodríguez,105
728,Uruguay,16,DF,1984-06-08,M. PEREIRA,FC Porto,173,73,POR,34.016438,Maxi Pereira,125
733,Uruguay,21,FW,1987-02-14,E. CAVANI,Paris Saint-Germain FC,188,78,FRA,31.328767,Edinson Cavani,101

In [ ]:
fig=px.bar(players_Cap,x='name',y='caps',color='caps',title='Players in the tournament with 100 or more caps')
fig.show()

ESSAM EL-HADARY is leader of caps he is 158,then sergio ramos(152) and cristian ronalod(150) these players reached 150 and above